POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "test",
    "author": "test",
    "url": "test",
    "likes": 0
}
###

GET http://localhost:3003/api/blogs/

###

GET http://localhost:3003/api/blogs/668e55a2422fcfef847a939c

    
    
